# Site settings
title: Paulonia Handbook
short_title: Paulonia Handbook
description: |
    Documentación de todos los procesos de Paulonia.
baseurl: ""
handbooks_path: "paulonia_handbook"
url: "http://opendatahandbook.org" # the base hostname & protocol for your handbook site
home: "https://paulonia.dev" # the base hostname & protocol for your main company site
company_logo: paulonia.png
github_username:  PauloniaAQP
github_repo:  paulonia_handbook
contact: https://paulonia.dev/contacto


devs:
  -
      name: Sam Smith
      github: mintcanary

contributors:
  -
      name: Rufus Pollock
      link: http://rufuspollock.org/



#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "paulonia_handbook/backend"
    values:
      layout: page
      section: Backend Handbook
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
